version: "3.7"

services:
  postgres:
    image: postgres:13.6-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cognito
    ports:
      - "5432:5432"